autodetect: yes
strictness: veryhigh
test-warnings: false
doc-warnings: true

ignore-paths:
  - .git
  - coverage
  - docs
  - lib
  - metrics
  - old
  - py_pov_env

ignore-patterns:
   - (^|/)skip(this)?(/|$)

pep8:
  run: true
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 79
    single-line-if-stmt: n

pylint:
  run: true

pep257:
  disable:
    - D203
  run: true

pyroma:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 10

dodgy:
  run: false

pyflakes:
  run: true

frosted:
  run: true

vulture:
  run: true


