"""
LGEO Libray Include File.

(C) lgeo@digitalbricks.org (Lutz Uhlmann)

19970623 Lutz Uhlmann
20071225 Lutz Uhlmann fixed stud orientation

This file is in no way related to the LEGO(tm) Group.
It is provided for private non-commercial use only.

lg_3024: Plate 1 x 1
"""

from lgeo.include.common.brick_subparts import standard_plate


def solid():
    """Return standard_plate(length, width), solid."""
    return standard_plate(1, 1)


# #declare lg_3024_clear =
# merge {
#  sphere {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE, LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE,
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  cylinder {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LG_CORNER_SPACE, LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_CORNER_SPACE>,
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  sphere {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, 
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>, LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   <LG_CORNER_SPACE, WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  cylinder {
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#   WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>,
#   LG_CORNER_SPACE
#  }
#  difference {
#   merge {
#    box {
#     <LG_CORNER_SPACE, LG_CORNER_SPACE, 0>,
#     <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#     WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_PLATE_HEIGHT>
#    }
#    box {
#     <0, LG_CORNER_SPACE, LG_CORNER_SPACE>,
#     <LENGTH*LG_BRICK_WIDTH,
#     WIDTH*LG_BRICK_WIDTH-LG_CORNER_SPACE, LG_PLATE_HEIGHT-LG_CORNER_SPACE>
#    }
#    box {
#     <LG_CORNER_SPACE, 0, LG_CORNER_SPACE>,
#     <LENGTH*LG_BRICK_WIDTH-LG_CORNER_SPACE,
#     WIDTH*LG_BRICK_WIDTH, LG_PLATE_HEIGHT-LG_CORNER_SPACE>
#    }
#   }
#   union {
#    box {
#     <LG_WALL_WIDTH, LG_WALL_WIDTH, -LG_CORNER_SPACE>,
#     <LENGTH*LG_BRICK_WIDTH-LG_WALL_WIDTH,
#     WIDTH*LG_BRICK_WIDTH-LG_WALL_WIDTH, LG_PLATE_INNER_HEIGHT>
#    }
#    object {
#     lg_knob_inner_space_clear
#     translate <0.5*LG_BRICK_WIDTH, 0.5*LG_BRICK_WIDTH, LG_PLATE_INNER_HEIGHT>
#    }
#   }
#  }
#  object {
#   lg_knob_clear
#   rotate <0, 0, -90>
#   translate <0.5*LG_BRICK_WIDTH, 0.5*LG_BRICK_WIDTH, LG_PLATE_HEIGHT>
#  }
#  translate <-LENGTH/2*LG_BRICK_WIDTH, -0.5*LG_BRICK_WIDTH, -LG_PLATE_HEIGHT>
#  rotate <0, 0, 90>
# }

# #end
